### ISSUE TITLE
User Stories til backlog for Apollo

### ISSUE THREAD

**Issue by ThomasRusbjerg** [SW709E19/Report#23]

**Comment by ThomasRusbjerg** [comment]
Rasmus har skrevet nogle user stories som kan findes på drive "work documents/Personas and user stories"

**Comment by Dbraae** [comment]
Jeg har læst alle de engelske stories, skrevet få kommentarer og rettet et par fejl

**Comment by icedandreas** [comment]
Har læst og sat kommentare i dokumentet.
